language: php
sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - CS_CHECKS=true
        - SEND_COVERAGE=true
        - PHPSTAN=true
        - INFECTION=true
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  # Debug Java version
  - java -version
  # Enable HHVM config
  - echo "hhvm.php7.all = 1" > /tmp/hhvm.php.ini
  - echo "hhvm.hack.lang.look_for_typechecker = 0" >> /tmp/hhvm.php.ini
  - phpenv config-add /tmp/hhvm.php.ini
  # Creating the test database
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_test_db;" -uroot
  - mysql -e "create database phpunit_soluble_test_db;" -uroot
  - zcat test/data/mysql/schema.sql.gz | mysql -uroot phpunit_soluble_test_db
  - zcat test/data/mysql/data.sql.gz | mysql -uroot phpunit_soluble_test_db
  # Setting up some directories
  - mkdir build
  - mkdir -p build/logs
  - mkdir -p test/logs
  # Build and launch a JavaBridge server in background
  - ./.travis/launch_javabridge_server.sh
  # On travis Javabridge needs some time to
  # be fully running, assume 6 seconds
  # and show the log file
  - sleep 6 && cat ./.travis/webapp-runner.8083.log
  - composer --ignore-platform-reqs install
    
script:
  - ./vendor/bin/phpunit -c .travis/phpunit.travis.xml -v --coverage-clover=coverage.xml
  - if [[ $CS_CHECKS == true ]]; then ./vendor/bin/php-cs-fixer --diff --dry-run -v fix; fi
  - if [[ $PHPSTAN == true ]]; then composer phpstan; fi
  - if [[ $INFECTION == true ]]; then ./vendor/bin/infection --test-framework=phpunit --test-framework-options="-c ./.travis/phpunit.travis.xml" --min-msi=20 --min-covered-msi=25 --threads=4; fi

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
